-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 20:06:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Soccer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Soccer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Soccer` ;
USE `Soccer` ;

-- -----------------------------------------------------
-- Table `Soccer`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Soccer`.`Team` (
  `TeamID` INT NOT NULL,
  `TeamName` VARCHAR(45) NOT NULL,
  `TeamBalDue` DECIMAL NULL,
  PRIMARY KEY (`TeamID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Soccer`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Soccer`.`Player` (
  `PlayerID` INT NOT NULL,
  `PlayerFirstName` VARCHAR(45) NOT NULL,
  `PlayerLastName` VARCHAR(45) NOT NULL,
  `PlayerDOB` DATE NOT NULL,
  `PlayerTeamID` INT NOT NULL,
  PRIMARY KEY (`PlayerID`),
  INDEX `PlayerTeamID_idx` (`PlayerTeamID` ASC) VISIBLE,
  CONSTRAINT `PlayerTeamID`
    FOREIGN KEY (`PlayerTeamID`)
    REFERENCES `Soccer`.`Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
